### ISSUE TITLE
No such file or directory after RUN chmod +x wpe-init step

### ISSUE THREAD

**Issue by greaterfool** [balena-io-projects/balena-wpe#33]
After running "balena push balenaDash" during the docker build I get an error:

panic: standard_init_linux.go:175: exec user process caused "no such file or directory"

Full output here: https://hastebin.com/iwixotecep

**Comment by StuartCarrison** [comment]
Bump. I have the same issue

I am building for a NUC application if that makes any difference

Step 1/7 : FROM petrosagg/resin-wpe:raspberrypi3-30c7465
 ---> 4b90e1c6a06a
Step 2/7 : COPY udev-rules/ /etc/udev/rules.d/
Using cache
 ---> 801296c43c60
Step 3/7 : COPY wpe-init /wpe-init
Using cache
 ---> 56c77d01e232
**Step 4/7 : RUN chmod +x wpe-init
 ---> Running in 12b9f22eaa8c
panic: standard_init_linux.go:175: exec user process caused "no such file or directory" [recovered]
        panic: standard_init_linux.go:175: exec user process caused "no such file or directory"**
goroutine 1 [running, locked to thread]:
panic(0x79d920, 0xc420136380)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/urfave/cli.HandleAction.func1(0xc420089748)
        /tmp/tmp.Xj6E6mk6ve/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/app.go:478 +0x247
panic(0x79d920, 0xc420136380)
        /usr/local/go/src/runtime/panic.go:458 +0x243
github.com/opencontainers/runc/libcontainer.(*LinuxFactory).StartInitialization.func1(0xc420089198, 0xc420026098, 0xc420089238)
        /tmp/tmp.Xj6E6mk6ve/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/opencontainers/runc/libcontainer/factory_linux.go:259 +0x18f
github.com/opencontainers/runc/libcontainer.(*LinuxFactory).StartInitialization(0xc420057450, 0xb98380, 0xc420136380)
        /tmp/tmp.Xj6E6mk6ve/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/opencontainers/runc/libcontainer/factory_linux.go:277 +0x353
main.glob..func8(0xc42008ca00, 0x0, 0x0)
        /tmp/tmp.Xj6E6mk6ve/src/github.com/opencontainers/runc/main_unix.go:26 +0x66
reflect.Value.call(0x788960, 0x813a88, 0x13, 0x7e6609, 0x4, 0xc420089708, 0x1, 0x1, 0x4ce1e8, 0x7dc460, ...)

        /usr/local/go/src/reflect/value.go:434 +0x5c8
reflect.Value.Call(0x788960, 0x813a88, 0x13, 0xc420089708, 0x1, 0x1, 0x0, 0xc4200896e8, 0x4d71c6)
        /usr/local/go/src/reflect/value.go:302 +0xa4
github.com/urfave/cli.HandleAction(0x788960, 0x813a88, 0xc42008ca00, 0x0, 0x0)
        /tmp/tmp.Xj6E6mk6ve/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/app.go:487 +0x1e0
github.com/urfave/cli.Command.Run(0x7e67d5, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7f7c23, 0x51, 0x0, ...)

        /tmp/tmp.Xj6E6mk6ve/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/command.go:191 +0xc3b
github.com/urfave/cli.(*App).Run(0xc4200d8000, 0xc42000c120, 0x2, 0x2, 0x0, 0x0)

        /tmp/tmp.Xj6E6mk6ve/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/app.go:240 +0x611
main.main()

/tmp/tmp.Xj6E6mk6ve/src/github.com/opencontainers/runc/main.go:137 +0xbd6

Removing intermediate container 12b9f22eaa8c
The command '/bin/sh -c chmod +x wpe-init' returned a non-zero code: 2

**Comment by alanpereiracoelho** [comment]
Boa tarde...
Tiveram algum sucesso estou com o mesmo problema?
