### ISSUE TITLE
Change timezone

### ISSUE THREAD

**Issue by marhoy** [balena-io-projects/balena-wpe#40]
I'm using balena-dash and wpe to show a dashboard that also shows the current time on the webbrowser client.

Inside the wpe-container, I need to change the timezone, but there's no zoneinfo-files under /usr/share/, so setting the TZ-variable has no effect.

How do I install the zoneinfo-files and change the timezone?

**Comment by marhoy** [comment]
If someone have the same problem and reads this: I figured out that Busybox (used in the resin-wpe image) has a different format for the TZ-variable. For Europe, I'm using
`TZ=CET-1CEST`

**Comment by idoodler** [comment]
@marhoy Where did you find that information? Do you know a list of timezones?

**Comment by marhoy** [comment]
@idoodler

It's documented in the glibc manual:
https://www.gnu.org/software/libc/manual/html_node/TZ-Variable.html#TZ-Variable
