### ISSUE TITLE
Not able to use two get parameters in the WPE_URL

### ISSUE THREAD

**Issue by ginnyTheCat** [balena-io-projects/balena-wpe#57]
If I insert a URL with two get parameters like example.com/?one=foo&two=bar in the console and on the screen example.com/?one=foo is loaded. Has the & to be escaped in the WPE_URL field or is this a bug?

**Comment by adamtester** [comment]
See this issue: https://github.com/balena-io-projects/balena-dash/issues/42

**Comment by ginnyTheCat** [comment]
Thanks
